import {Dimensions, StyleSheet} from 'react-native';
import {COLORS, FONTS} from '../constants';
import {getWidth, setHeight, setWidth} from './Dimension';

export const styles = StyleSheet.create({
  centeredView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.5)',
  },
  modalView: {
    paddingVertical: 10,
    marginHorizontal: 20,
    width: Dimensions.get('screen').width - 40,
    backgroundColor: '#fff',
    borderRadius: 6,
    // alignItems: 'center',
  },
  button: {
    height: 45,
    width: 45,
    borderRadius: 6,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#fff',
    alignSelf: 'flex-end',
  },
  button2: {
    borderRadius: 4,
    width: '40%',
    height: 42,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: COLORS.DEFAULT_COLOR,
    marginBottom: 30,
  },
  button3: {
    borderRadius: 4,
    width: '40%',
    height: 42,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#F15A24',
    marginBottom: 30,
  },
  textStyle: {
    color: COLORS.textColor,
    fontWeight: 'bold',
    textAlign: 'center',
    fontSize: 17,
  },
  modalTitle: {
    // fontWeight: 'bold',
    // textAlign: 'center',
    color: COLORS.textColor,
    fontFamily: FONTS.bold,
    // marginLeft: 20,
    fontSize: 24,
  },
  modalTitle2: {
    // fontWeight: 'bold',
    // textAlign: 'center',
    color: COLORS.textColor,
    fontFamily: FONTS.bold,
    fontWeight: 'bold',
    marginLeft: 20,
    fontSize: 15,
    width: '70%',
  },
  modalText: {
    // color: ,
    fontSize: 16,
    fontWeight: 'normal',
    marginVertical: 5,
    textAlign: 'center',
  },
  modalText2: {
    color: COLORS.textColor,
    fontSize: 15,
  },
  dialogButtonBackground: {
    width: '100%',
    marginTop: 30,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
  },

  buttonBackground: {
    backgroundColor: '#fff',
    borderTopRightRadius: 30,
    borderTopLeftRadius: 30,
    borderBottomRightRadius: 10,
    borderBottomLeftRadius: 10,
    width: '100%',
    marginTop: 30,
    paddingVertical: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },

  loader: {
    height: setHeight(40),
    marginHorizontal: 20,
    width: getWidth() - 40,
    backgroundColor: 'green',
    borderRadius: 10,
    paddingTop: 40,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  // input alert
  inputContainer: {
    width: '100%',
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: setHeight(1.5),
  },
  labelContainer: {
    alignSelf: 'flex-start',
    position: 'absolute',
    top: -setHeight(0.7),
    left: setWidth(13),
    zIndex: 1,
    backgroundColor: 'green',
    paddingHorizontal: setWidth(5),
    paddingVertical: setHeight(0.3),
    borderRadius: 10,
  },
  label: {
    color: COLORS.textColor,
    fontSize: setHeight(1.6),
  },
  input: {
    // borderWidth: 1,
    // borderColor: "#a0a0a0",
    marginTop: setHeight(1),
    width: '80%',
    borderRadius: 10,
    backgroundColor: '#fff',
  },
});
